# Generated by Django 4.2 on 2024-05-28 17:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import students.utils.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "first_name",
                    models.CharField(
                        max_length=120,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            students.utils.validators.first_name_validator,
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=120,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars"),
                ),
                ("email", models.EmailField(max_length=120)),
                ("grade", models.PositiveIntegerField(default=0)),
                ("birth_date", models.DateField(null=True)),
                (
                    "gpa",
                    models.FloatField(
                        default=0,
                        null=True,
                        validators=[students.utils.validators.gpa_validator],
                    ),
                ),
                ("department", models.CharField(max_length=120, null=True)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="groups.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ("first_name",),
            },
        ),
    ]
