# Generated by Django 4.2 on 2024-04-25 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("students", "0002_alter_student_options_alter_student_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                default="exit",
                on_delete=django.db.models.deletion.CASCADE,
                to="groups.group",
            ),
            preserve_default=False,
        ),
    ]
