# Generated by Django 4.2 on 2024-04-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_remove_student_id_student_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars"),
        ),
    ]
