# Generated by Django 4.2 on 2024-04-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_student_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes"),
        ),
    ]
