# Generated by Django 4.2 on 2024-05-12 20:04

from django.db import migrations, models
import students.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_student_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="gpa",
            field=models.FloatField(
                default=0,
                null=True,
                validators=[students.utils.validators.gpa_validator],
            ),
        ),
    ]
