# Generated by Django 4.2 on 2024-05-28 17:45

import django.core.validators
from django.db import migrations, models
import students.utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=120,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            students.utils.validators.first_name_validator,
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=120,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars"),
                ),
                ("age", models.IntegerField(default=0)),
                ("experience", models.PositiveIntegerField(default=0)),
                ("salary", models.PositiveIntegerField(default=0)),
                (
                    "sex",
                    models.CharField(
                        choices=[("W", "Woman"), ("M", "Man")], max_length=1
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "groups",
                    models.ManyToManyField(related_name="teachers", to="groups.group"),
                ),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
            },
        ),
    ]
