# Generated by Django 4.2 on 2024-04-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("age", models.IntegerField(default=0)),
                ("experience", models.PositiveIntegerField(default=0)),
                ("salary", models.PositiveIntegerField(default=0)),
                (
                    "sex",
                    models.CharField(choices=[("W", "Woman"), ("M", "Man")], max_length=1),
                ),
                ("subject", models.CharField(max_length=255)),
            ],
        ),
    ]
