# Generated by Django 4.2 on 2024-04-25 10:20

import django.core.validators
from django.db import migrations, models
import students.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0003_teacher_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(
                max_length=120,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    students.utils.validators.first_name_validator,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(
                max_length=120,
                null=True,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="sex",
            field=models.CharField(
                choices=[("W", "Woman"), ("M", "Man")], max_length=1
            ),
        ),
    ]
