# Generated by Django 4.2 on 2024-04-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0004_alter_teacher_first_name_alter_teacher_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="sex",
            field=models.CharField(
                choices=[("M", "Man"), ("W", "Woman")], max_length=1
            ),
        ),
    ]
