# Generated by Django 4.2 on 2024-04-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0005_alter_teacher_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes"),
        ),
    ]
