# Generated by Django 4.2 on 2024-04-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0006_teacher_avatar_teacher_resume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="resume",
        ),
    ]
