# Generated by Django 4.2 on 2024-04-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0007_remove_teacher_resume"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="group",
            new_name="groups",
        ),
    ]
