# Generated by Django 4.2 on 2024-05-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0008_rename_group_teacher_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="sex",
            field=models.CharField(
                choices=[("W", "Woman"), ("M", "Man")], max_length=1
            ),
        ),
    ]
