# Generated by Django 4.2 on 2024-05-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_group_max_count_of_students"),
        ("teachers", "0009_alter_teacher_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="groups",
            field=models.ManyToManyField(related_name="teachers", to="groups.group"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="sex",
            field=models.CharField(
                choices=[("M", "Man"), ("W", "Woman")], max_length=1
            ),
        ),
    ]
