# Generated by Django 4.2 on 2024-05-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0010_alter_teacher_groups_alter_teacher_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="sex",
            field=models.CharField(
                choices=[("W", "Woman"), ("M", "Man")], max_length=1
            ),
        ),
    ]
