# Generated by Django 4.2 on 2024-05-12 20:04

from django.db import migrations, models
import students.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="gpa",
            field=models.FloatField(
                default=0,
                null=True,
                validators=[students.utils.validators.gpa_validator],
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="median_age",
            field=models.FloatField(
                default=0,
                null=True,
                validators=[students.utils.validators.median_age_validator],
            ),
        ),
    ]
