# Generated by Django 4.2 on 2024-05-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_group_gpa_group_median_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="max_count_of_students",
            field=models.PositiveIntegerField(default=20, null=True),
        ),
    ]
